services:
  bun:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: tail -f /dev/null
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19003:19003"
