#!/bin/sh

# Detect bun and run it write pretty error when bun is not found

# Define colors
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if bun is installed
which bun >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo -e "${RED}❌ bun could not be found${NC}"
    echo -e "💡 Please install bun by running '${RED}npm install -g bun${NC}'"
    exit 1
fi

# Run bun
bun bunner/entry.ts $@
