#!/bin/bash

source ./bunner/run_in_bun_docker.sh

export COLUMNS=$(tput cols)
export LINES=$(tput lines)

out=$(
    cd ./bunner
    export WORK_DIR=$(pwd)
    run_in_bun_docker entry.ts $@
)

res=$?

if [ $res -eq 4 ]; then
    cmd=$(echo "$out" | tr -d '\r')
    $cmd
else
    echo "$out"
    exit $res
fi
