#!/bin/bash

WORK_DIR=$(pwd)
BUN_EXEC=$(realpath "./bunner/bun")
ENTRY_FILE=$(realpath "./bunner/entry.ts")

out=$($BUN_EXEC "$ENTRY_FILE" $@)
res=$?

if [ $res -eq 4 ]; then
    cmd=$(echo "$out" | tr -d '\r')
    $cmd
else
    echo "$out"
    exit $res
fi
